apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v8h6xc4ll-java-quarkus
  janus-idp.io/tekton: v8h6xc4ll-java-quarkus
  backstage.io/kubernetes-id: v8h6xc4ll-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v8h6xc4ll-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
